server.port=8080
spring.application.name=BATTLE_ARENA

spring.mvc.static-path-pattern=/**
spring.web.resources.static-locations=classpath:/static/
logging.level.root=INFO
logging.level.com.battlearena=DEBUG